global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:

scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: ['192.168.0.17:9100']
      labels:
        instance: 'localhost'