# VM creating:
MACHINES = {
  # VM name
  :"kernel-update" => {
              # Define VM OS
              :box_name => "generic/centos8s",
              # VM kernel version
              :box_version => "4.3.4",
              # VM CPUs
              :cpus => 2,
              # VM RAM 
              :memory => 1024,
            }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    # Disabling VM shared folder
    config.vm.synced_folder ".", "/vagrant", disabled: true
    # VM config
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.host_name = boxname.to_s
      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end
    end
  end
end
