# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install  = true
  end
  config.vm.box = "bento/ubuntu-22.04"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.define "client" do |client|
    client.vm.network "private_network", ip: "192.168.56.150"
    client.vm.hostname = "client"
    client.vm.provision "file", source: "files/", destination: "/tmp/"
    client.vm.provision "shell", path: "client.sh"
  end

  config.vm.define "backup" do |backup|
    backup.vm.network "private_network", ip: "192.168.56.160"
    backup.vm.hostname = "backup"
    backup.vm.provision "shell", path: "backup.sh"
  end
end
